# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "WuxinrongY"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 50

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Computer Vision and Pattern Recognition":
        filters: ["object detection", "small object detection", "image classification", 
                  "image segmentation", "image generation", 
                  "image synthesis", "image restoration", "image super-resolution", "3D Reconstruction", "Pose Estimation", 
                  "Optical Flow", "Video Analysis", 
                  "Action Recognition", "Image Captioning"]
    "Image Matching":
        filters: ["Image Matching", "Keypoint Matching", 
                  "Line Segment Detection", "Local Feature Matching"]
    "Computation and Language":
        filters: ["Vision and Language", "Image Captioning", 
                  "Visual Question Answering", "Multimodal Learning"]
    "Artificial Intelligence":
        filters: ["Reinforcement Learning", "Meta Learning", 
                  "Neural Architecture Search", "AutoML"]
    "Machine Learning":
        filters: ["Self-Supervised Learning", "Contrastive Learning", 
                  "Generative Models", "Domain Adaptation", 
                  "Federated Learning", "Causal Learning"]
    